import os
from datetime import datetime
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from fpdf import FPDF

from app.db import get_db
from app.models import Prescription, SymptomRecord
from pydantic import BaseModel

router = APIRouter()

# ✅ Always save inside backend/generated_pdfs
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PDF_DIR = os.path.join(BASE_DIR, "generated_pdfs")
os.makedirs(PDF_DIR, exist_ok=True)

class PrescriptionRequest(BaseModel):
    symptom_record_id: int
    prescription_body: str


def generate_prescription_pdf(symptom_record, prescription_body: str, user_email: str):
    """Generate a professional PDF prescription with disease details and risk alert."""

    pdf = FPDF()
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "AI Health Assistant - Prescription", ln=True, align="C")

    pdf.set_font("Helvetica", size=12)
    pdf.ln(5)
    pdf.cell(0, 10, f"Email: {user_email}", ln=True)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.ln(5)

    # Section Line
    pdf.set_draw_color(0, 0, 0)
    pdf.set_line_width(0.3)
    pdf.line(10, 40, 200, 40)
    pdf.ln(10)

    # Disease Name
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Predicted Disease:", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.multi_cell(0, 8, symptom_record.predicted_disease or "N/A")
    pdf.ln(3)

    # Disease Description (if available)
    if getattr(symptom_record, "disease_description", None):
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "Disease Description:", ln=True)
        pdf.set_font("Helvetica", "", 12)
        pdf.multi_cell(0, 8, symptom_record.disease_description)
        pdf.ln(5)

    # Extracted Symptoms
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Extracted Symptoms:", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.multi_cell(0, 8, symptom_record.extracted_symptoms or "N/A")
    pdf.ln(5)

    # Risk Score
    risk_score = getattr(symptom_record, "risk_score", None)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Risk Score:", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.multi_cell(0, 8, f"{risk_score:.2f}" if risk_score is not None else "N/A")
    pdf.ln(5)

    # 🚨 High Risk Warning
    if risk_score and risk_score >= 0.7:
        pdf.set_text_color(255, 0, 0)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "⚠️ EMERGENCY ALERT:", ln=True)
        pdf.set_font("Helvetica", "", 12)
        pdf.multi_cell(0, 8, "High risk detected! Please seek immediate medical attention.")
        pdf.ln(5)
        pdf.set_text_color(0, 0, 0)

    # Prescription or Recommendations
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Prescription / Recommendations:", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.multi_cell(0, 8, prescription_body or "No additional notes provided.")
    pdf.ln(10)

    # Footer
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 10, "Generated by AI Health Assistant", ln=True, align="C")

    # ✅ File naming: user_email_date_time.pdf
    safe_email = user_email.replace("@", "_").replace(".", "_")
    filename = f"{safe_email}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(PDF_DIR, filename)

    pdf.output(filepath)

    if not os.path.exists(filepath):
        raise HTTPException(status_code=500, detail="Failed to save PDF file")

    return filepath



@router.post("/generate")
def generate_prescription(request: PrescriptionRequest, db: Session = Depends(get_db)):
    """Generate and store a prescription in the database."""
    record = db.query(SymptomRecord).filter(SymptomRecord.id == request.symptom_record_id).first()
    if not record:
        raise HTTPException(status_code=404, detail="Symptom record not found")

    user_email = getattr(record.user)  # fallback email
    file_path = generate_prescription_pdf(record, request.prescription_body, user_email)

    pres = Prescription(user_id=record.user_id, pdf_url=file_path)
    db.add(pres)
    db.commit()
    db.refresh(pres)

    return {
        "message": "Prescription generated successfully",
        "pdf_url": file_path.replace("\\", "/"),
    }


@router.get("/download/{prescription_id}")
def download_prescription(prescription_id: int, db: Session = Depends(get_db)):
    """Serve the stored prescription PDF to the client."""
    pres = db.query(Prescription).filter(Prescription.id == prescription_id).first()
    if not pres:
        raise HTTPException(status_code=404, detail="Prescription not found")

    if not os.path.exists(pres.pdf_url):
        raise HTTPException(status_code=404, detail="PDF file not found")

    return FileResponse(
        path=pres.pdf_url,
        media_type="application/pdf",
        filename=os.path.basename(pres.pdf_url),
    )
